### ISSUE TITLE
Delay for streamers. 

### ISSUE THREAD

**Issue by JamzWhamz** [Pogify/pogify#14]
So you know how twitch and YouTube have stream delay. Well, I’m thinking of being able to time the music up with your stream using the “delay” feature. The “delay” feature could be used because of lag, or because your stream has delay enabled (darn stream snipers). This could actually be a very useful feature for people watching as well. You could possibly time the music up with the streamer by moving a delay slider, or putting in an exact number. Sessions could have this default enabled based on your connection to the servers to compensate for lag or ping. **Honestly I would love to see this added into pogify.** With all this said, thanks for reading I hope you add this feature.

**Comment by jeongY-Cho** [comment]
Hi JamzWhamz. Thanks for the feature request. This is something we'll definitely consider implementing in the future
